name: Remove disabled packages

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/remove-disabled-pacakges.yml
  schedule:
    # Once every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: remove-disabled-packages
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  remove-disabled-packages:
    # if: github.repository_owner == 'Homebrew'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    env:
      REMOVAL_BRANCH: remove-disabled-packages
    permissions:
      contents: write # for Homebrew/actions/git-try-push
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Run brew tap
        id: tap
        run: brew tap bevanjkay/tap

      - name: Configure Git user
        id: git-user-config
        uses: Homebrew/actions/git-user-config@master
        with:
          # username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'bkdbot' }}
          username: bkdbot

      - name: Checkout removal branch
        run: git checkout -b "$REMOVAL_BRANCH" origin/main
        working-directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/bevanjkay/homebrew-tap

      - name: Remove disabled packages
        id: remove_disabled
        uses: bevanjkay/actions/remove-disabled-packages@master
        env:
          HOMEBREW_EVAL_ALL: 1
        
      - name: Debug output
        run: echo "${{ toJson(steps.remove_disabled) }}"

      - name: Push commits
        if: fromJson(steps.remove_disabled.outputs.packages-removed)
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ secrets.BOT_TOKEN }}
          directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/bevanjkay/homebrew-tap
          branch: ${{ env.REMOVAL_BRANCH }}
        env:
          GIT_COMMITTER_NAME: "${{ steps.git-user-config.outputs.name }}"
          GIT_COMMITTER_EMAIL: "${{ steps.git-user-config.outputs.email }}"
  
      - name: Create pull request
        id: pr-create
        if: fromJson(steps.remove_disabled.outputs.packages-removed)
        working-directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/bevanjkay/homebrew-tap
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          PR_BODY: >
            This pull request was created automatically by the
            [`remove-disabled-packages`](https://github.com/Homebrew/homebrew-core/blob/HEAD/.github/workflows/remove-disabled-formulae.yml)
            workflow.
        run: |
          gh pr create \
            --base main \
            --body "$PR_BODY" \
            --head "$REMOVAL_BRANCH" \
            --title 'Remove disabled packages'
