name: Remove disabled formulae

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/remove-disabled-formulae.yml
  schedule:
    # Once every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: remove-disabled-formulae
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  remove-disabled-formulae:
    # if: github.repository_owner == 'Homebrew'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    env:
      REMOVAL_BRANCH: remove-disabled-packages
    permissions:
      contents: write # for Homebrew/actions/git-try-push
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'bkdbot' }}

      - name: Checkout removal branch
        run: git checkout -b "$REMOVAL_BRANCH" origin/main
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}

      - name: Remove disabled packages
        id: remove_disabled
        uses: bevanjkay/actions/remove-disabled-packages@master
        env:
          HOMEBREW_EVAL_ALL: 1

      - name: Push commits
        if: fromJson(steps.remove_disabled.outputs.formulae-removed)
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ secrets.BOT_TOKEN }}
          directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
          branch: ${{ env.REMOVAL_BRANCH }}

      - name: Create pull request
        id: pr-create
        if: fromJson(steps.remove_disabled.outputs.formulae-removed)
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          PR_BODY: >
            This pull request was created automatically by the
            [`remove-disabled-packages`](https://github.com/Homebrew/homebrew-core/blob/HEAD/.github/workflows/remove-disabled-formulae.yml)
            workflow.
        run: |
          gh pr create \
            --base master \
            --body "$PR_BODY" \
            --head "$REMOVAL_BRANCH" \
            --title 'Remove disabled packages'
