name: Re-run Workflow

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  pull_request_target:
    types:
      - closed
      - labeled
      - unlabeled
  schedule:
    - cron: '30 */3 * * *' # every 3 hours (30 minutes past the hour)

permissions:
  contents: read

jobs:
  rerun-workflow:
    if: >
      (
        github.event.label.name == 'ci-requeue' ||
        github.event.label.name == 'ci-retry' ||
        github.event.label.name == 'ci-skip-install' ||
        github.event.label.name == 'ci-syntax-only' ||
        !github.event.label.name
      )
    runs-on: ubuntu-latest
    steps:
      - name: Re-run CI workflow
        uses: reitermarkus/rerun-workflow@440187d88f68a23cfb30caab5f33ac1bcce31b6a
        with:
          token: ${{ secrets.BOT_TOKEN }}
          once-label: ci-requeue
          continuous-label: ci-retry
          trigger-labels: ci-skip-install,ci-syntax-only
          workflow: ci.yml

  rerun-failed-jobs:
    if: >
      (
        github.event.label.name == 'ci-requeue-failed-jobs' ||
        github.event.label.name == 'ci-retry-failed-jobs' ||
        github.event.label.name == 'ci-skip-install' ||
        github.event.label.name == 'ci-syntax-only' ||
        !github.event.label.name
      )
    runs-on: ubuntu-latest
    steps:
      - name: Re-run CI workflow
        uses: reitermarkus/rerun-workflow@440187d88f68a23cfb30caab5f33ac1bcce31b6a
        with:
          token: ${{ secrets.BOT_TOKEN }}
          once-label: ci-requeue-failed-jobs
          continuous-label: ci-retry-failed-jobs
          trigger-labels: ci-skip-install,ci-syntax-only
          workflow: ci.yml
